name: guide_point
description: A Flutter app that scans QR codes and gives voice output for indoor navigation.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  # Core Functionality & UI
  cupertino_icons: ^1.0.6
  mobile_scanner: ^3.5.5
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.3

  # Voice, Speech, and Hardware Keys
  flutter_tts: ^3.8.3
  volume_controller: ^3.4.0 # Correct, current version
  speech_to_text: ^6.6.1      # Corrected indentation and version

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Icons/app_icon.png"
  min_sdk_android: 23

# Flutter Assets
flutter:
  uses-material-design: true
  assets:
    - assets/Icons/app_icon.png # Includes all files in this directory